api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "order-limit-100k"
type = "function"
uid = "ec019e41-e363-d7b6-c36e-062eac0a9323ca4613c8"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
